### ISSUE TITLE
SEGFAULT in DTCMP_Rankv_sort from scr's test_api_multiple

### ISSUE THREAD

**Issue by rhaas80** [LLNL/dtcmp#4]
I get segfaults in SCR's `test_api_multiple`. A backtrace is:

```
0x00007ffff7ed75f6 in PMPI_Type_get_extent () from /usr/lib/x86_64-linux-gnu/libmpi.so.40
(gdb) up
#1  0x00007ffff7c2b064 in DTCMP_Rankv_sort (count=count@entry=0, buf=0x0,
    groups=groups@entry=0x7fffffffb3a0, group_id=group_id@entry=0x0,
    group_ranks=group_ranks@entry=0x0, group_rank=group_rank@entry=0x0, key=0x9, keysat=0x9, cmp=0x0,
    hints=0, comm=0x55555559dfe0) at dtcmp_rankv_sort.c:512
512       MPI_Type_get_extent(keysat, &keysat_lb, &keysat_extent);
(gdb)
#2  0x00007ffff7c2c4ac in DTCMP_Rankv_strings_sort (count=0, strings=<optimized out>,
    groups=0x7fffffffb3a0, group_id=0x0, group_ranks=0x0, group_rank=0x0, hints=0, comm=0x55555559dfe0)
    at dtcmp_rankv_sort.c:703
703       int rc = DTCMP_Rankv_sort(
(gdb)
#3  0x00007ffff7fa90d2 in scr_assign_ownership (map=0x555555718810, bypass=1)
    at /data/rhaas/ncsa/LLNL/scr/src/scr.c:1288
1288      int dtcmp_rc = DTCMP_Rankv_strings(
(gdb) bt
#0  0x00007ffff7ed75f6 in PMPI_Type_get_extent () from /usr/lib/x86_64-linux-gnu/libmpi.so.40
#1  0x00007ffff7c2b064 in DTCMP_Rankv_sort (count=count@entry=0, buf=0x0,
    groups=groups@entry=0x7fffffffb3a0, group_id=group_id@entry=0x0,
    group_ranks=group_ranks@entry=0x0, group_rank=group_rank@entry=0x0, key=0x9, keysat=0x9, cmp=0x0,
    hints=0, comm=0x55555559dfe0) at dtcmp_rankv_sort.c:512
#2  0x00007ffff7c2c4ac in DTCMP_Rankv_strings_sort (count=0, strings=<optimized out>,
    groups=0x7fffffffb3a0, group_id=0x0, group_ranks=0x0, group_rank=0x0, hints=0, comm=0x55555559dfe0)
    at dtcmp_rankv_sort.c:703
#3  0x00007ffff7fa90d2 in scr_assign_ownership (map=0x555555718810, bypass=1)
    at /data/rhaas/ncsa/LLNL/scr/src/scr.c:1288
#4  0x00007ffff7fa930d in scr_complete_output (valid=1) at /data/rhaas/ncsa/LLNL/scr/src/scr.c:1366
#5  0x00007ffff7fac392 in SCR_Complete_output (valid=1) at /data/rhaas/ncsa/LLNL/scr/src/scr.c:2909
#6  0x0000555555557407 in main (argc=1, argv=0x7fffffffc778)
    at /data/rhaas/ncsa/LLNL/scr/examples/test_api_multiple.c:236
```

and one can turns this into an MPI error due to invalid datatype by changing:

```#diff
diff --git a/src/dtcmp_rankv_sort.c b/src/dtcmp_rankv_sort.c
index f3ab633..da28300 100644
--- a/src/dtcmp_rankv_sort.c
+++ b/src/dtcmp_rankv_sort.c
@@ -695,8 +695,8 @@ int DTCMP_Rankv_strings_sort(
   }

   /* build type to use as key and keysat types */
-  MPI_Datatype type_string;
-  DTCMP_Op cmp_string;
+  MPI_Datatype type_string = 0;
+  DTCMP_Op cmp_string = 0;
   DTCMP_Str_create_ascend(allmax, &type_string, &cmp_string);
```

**Comment by adammoody** [comment]
Released in https://github.com/LLNL/dtcmp/releases/tag/v1.1.1
